# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            John Devine
tagline:          'Personal Website'
description:      'Developer with a background in hospitality and a passion for world languages and cultures.'
url:              https://jpatrickdevine.info
baseurl:          

author:
  name:           'John Devine'
  url:            https://jpatrickdevine.info

paginate:         3
plugins_dir:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

gems: [jekyll-paginate]

github:
  repo:           https://github.com/jpatrickdevine/jpatrickdevine.github.io
